@startuml
'title Сценарий "Заполнение карточки курса"
legend top left
Предусловия:
1. Пользователь должен быть авторизован.
2. Системы должны быть доступны.

|= Сущность|= Описание |
|КоКу| Конструктор курсов |
|ИСы СПО| Продукты (сервисы) для колледжей |
|ИСы СОО| Продукты (сервисы) для школ |
endlegend

actor "Роль: 1,2" as User
participant "КоКу" as KK
participant "ИСы СОО" as SaaS_SOO
participant "ИСы СПО" as SaaS_SPO

User -> KK : Создать курс
KK --> User : Карточка курса
group Ввод текста
User -> KK : Название\nКраткое описание\nДлительность\nДата создания
end group 
User -> KK : Ввод списков (общее)
KK -> KK: Обложка курса\nАвтор курса\nУровень подготовки\nУровень изучения
User -> KK : Ввод списков [альт.]
alt Роль 1: Разработчик контента
KK -> SaaS_SOO : Параллель\nПредмет\nТема и ДЕ
else Роль 2: Методист СПО
KK -> SaaS_SPO : Номер курса (год обучения)\nПрофессия/Специальность\nКвалификация\nДисциплина\nЦикл курса\nТема и ДЕ
end alt
User -> KK : Сохранить курс
KK -> KK: Сохранить данные
KK --> User : Карточка курса
@enduml
