@startuml
!config=%load_json("https://dchizhikov.github.io/UML/orders_examples/config.json")

!include config.objects
!age = config.age

Customer "1" --> "0..*" Order : делает > age
Order "0..*" o- "1..*" Product : включает >
Product "0..*" <-up- "1" Provider : делает <
Product "1" *--> "1..*" Product : состоит
Order "1..*" <-- "1" Delivery : везет <
Product "0..*" <-- "1..*" Stock : хранит <
@enduml