@startuml
%set_variable_value("objects", "https://raw.githubusercontent.com/dchizhikov/UML/master/orders_examples/objects.puml")
!include objects

Customer "1" --> "0..*" Order : делает >
Order "0..*" o- "1..*" Product : включает >
Product "0..*" <-up- "1" Provider : делает <
Product "1" *--> "1..*" Product : состоит
Order "1..*" <-- "1" Delivery : везет <
Product "0..*" <-- "1..*" Stock : хранит <
@enduml
