@startuml
%set_variable_value("String", "text")
%set_variable_value("Integer", "int")
!Float = "real64"
!Date = "datetime"

object "Покупатель" as Customer{
    +id: Integer
    +имя: String
    +email: String
    +createOrder(Order)
} 

object "Товар" as Product{
    +id: Integer
    +название: String
    +цена: Float
    +addProduct(Product)
}

object "Заказ" as Order{
    +id: Integer
    +дата: Date
    +статус: String
    +addProduct(Product)
    +deleteProduct(Product)
}

object "Поставщик" as Provider{
    +id: Integer
    +название: String
    +контакты: String
}

object "Курьер" as Delivery{
    +id: Integer
    +имя: String
    +контакты: String
}

object "Склад" as Stock{
    +id: Integer
    +название: String
    +контакты: String
    +addProduct(Product)
    +deleteProduct(Product)
}
@enduml
