@startuml
'left to right direction

actor "Методист СПО/\nРазработчик контента" as Contenter
actor "Преподаватель СПО/\nУчитель" as Teacher
actor "Студент СПО/\nУчащийся" as Student
actor "Куратор" as Curator

package P0 as "Общие кейсы" {
    (Просмотр каталога курсов) as UC1
    (Фильтрация курсов) as UC2
    (Просмотр своих курсов\n[не надо]) as UC15
    (Сортировка курсов\n[нет, но надо?]) as UC2_1
    (Поиск курсов\n[нет, но надо]) as UC2_2
    (Просмотр курса\n[нет, но надо]) as UC3_0
    (Отображение при назначении курса\n[не надо]) as UC3_0_1
    (Отображение при самостоятельной записи на курс\n[не надо]) as UC3_0_2
    (Просмотр прогресса по курсу) as UC3
}

package P_A as "Кейсы поддержки" {
package P1 as "Кейсы администрирования курсов" {
    (Заполнение карточки курса) as UC4
    (Формирование структуры курса) as UC5
    (Наполнение курса контентом) as UC6
    (Публикация курса) as UC7
    (Редактирование курса\n[есть, но пуст]) as UC8
    (Архивация курса) as UC9
    (Просмотр статистики изучения курса) as UC9_1
    (Выгрузка прогресса курса\n[нет, но надо?]) as UC12
}
package P5 as "Кейсы (сервисные)" {
    (Уведомления\n[нет, но надо]) as UC18
}
}

package P_B as "Кейсы курсов" {
package P2 as "Кейсы управления обучением" {
    (Назначение курса) as UC10
    (Оценивание заданий курса) as UC11
    (Жалоба на курс) as UC12a
}

package P3 as "Кейсы обучения" {
    (Запись на курс [самостоятельно]) as UC13
    (Прохождение курса) as UC16
}

package P4 as "Кейсы курирования (СПО) обучения" {
    (Просмотр прогресса студентов по курсам) as UC17
}
}

'Связи между ролями и пакетами
P0 --[hidden]--> P_A
P_A --[hidden]--> P_B
Contenter --> P1
Teacher -u--> P2
Student -u--> P3
Curator -u--> P4

'Временно - связи со шлаком
UC2 -- UC15
UC3_0 -- UC3_0_1
UC3_0 -- UC3_0_2
@enduml
