@startuml
[*] --> Опубликованный

Опубликованный --> В_Процессе : Назначен преподавателем/учителем 
Опубликованный --> На_Редактировании : Редактирование

В_Процессе --> На_Редактировании : Редактирование

На_Редактировании --> Опубликованный : Завершение редактирования
На_Редактировании --> В_Процессе : Завершение редактирования

Опубликованный --> Архив : Архивирование
В_Процессе --> Архив : Архивирование

Архив --> [*]

note right of Опубликованный
    Роли: 
    - Учащийся
    - Студент СПО
    - Преподаватель СПО
    - Учитель
    - Методист СПО
    - Разработчик контента
end note

note right of В_Процессе
    Роли: 
    - Учащийся
    - Студент СПО
    - Преподаватель СПО
    - Учитель
    - Куратор
end note

note right of На_Редактировании
    Роли: 
    - Учащийся
    - Студент СПО
    - Преподаватель СПО
    - Учитель
    - Методист СПО
    - Разработчик контента
end note

note right of Архив
    Роли: 
    - Методист СПО
    - Разработчик контента
end note

@enduml
