@startuml
!procedure $components($name1, $name2)
  component $name1 as system_1 <<subsystem>>
  component $name2 as system_2 <<subsystem>>
!endprocedure
!procedure $interfaces($name1, $name2)
  () $name1 as iF_1: JSON
  () $name2 as iF_2
!endprocedure
@enduml
