@startuml
!procedure $components($names, $arg)
  !while $arg!=0
    !$name=$names.name[$arg]
    !$ps_name = "system_"+$arg
    [Component $name] as $ps_name <<subsystem>>
    !$arg = $arg - 1
  !endwhile

!endprocedure
!procedure $interfaces($name1, $name2)
  () $name1 as iF_1
  () $name2 as iF_2
!endprocedure
@enduml
