@startuml
'skinparam linetype polyline
skinparam linetype ortho

skinparam component {
    backgroundColor<<subsystem>> aqua-white
    backgroundColor blue/white
}
skinparam interface {
    backgroundColor aqua/white
}
@enduml
